### ISSUE TITLE
Multiple streams not in sync

### ISSUE THREAD

**Issue by sazz** [lperrin/node_airtunes#16]
I'm running a setup of three raspberry pi's with shairport and a central node.js serving the streams via airtunes.

I'm currently running into sync issues because i cannot get my clients to play the audio in sync. The lag between the clients is sometimes up to 2 seconds.

Do you have any clue what's the issue here?

Thanks,

sazz

**Comment by fritz-fritz** [comment]
@sazz , @lperrin 
FYI you may be interested in https://github.com/mikebrady/shairport-sync as that is supposed to keep the player synced with the source...

I'm planning to build a similar multi-airplay controller.

**Comment by fritz-fritz** [comment]
@lperrin I finally got everything set up and configured... I too have bad synchronization problems. I have set up streaming to many different types of airplay receivers and they all play out of sync (including the apple tv). It's odd... like the degradation is worse for each device sequentially.

Perhaps i'm adding the devices in a different manner than the way it was designed? Can you give sample code of how multiple receivers should be initialized?
