### ISSUE TITLE
Airport Express - Not working

### ISSUE THREAD

**Issue by microadam** [lperrin/node_airtunes#35]
Not having much luck getting this to work with an airport express (model A1264). It gets as far as sending the RECORD request, but never gets a response back from the airport express.

Any thoughts on where to debug this further?

Thanks

**Comment by microadam** [comment]
Turns out to talk to any official apple products, you cant use the hostname to connect, you have to use the routable IP address i.e AirPort.local wont work, you have to use 192.168.x.x for example. Tested this on 2 airport expresses and an apple TV

Using AirPort.local style works fine with Airport emulators like Kodi though

Some more info here: https://github.com/hfujita/pulseaudio-raop2/issues/21

**Comment by luan007** [comment]
This is greatly helpful, thank you
